layout improving
UdovikArtem/PokemonProject pull request #2
Opened 2024-06-18 18:59 UTC by UdovikArtem

### Changed info page and added new pokemons in main page

Main page:

![image](https://github.com/UdovikArtem/PokemonProject/assets/99731005/e3f96c43-cf8c-49af-9125-0228f061de27)

Info page:

![image](https://github.com/UdovikArtem/PokemonProject/assets/99731005/95157a6c-8f4e-41d9-9434-748cff4d51d9)

2024-06-18 21:31 UTC, pzinkevich42innowise requested changes

2024-06-18 21:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/AboutPokemonActivity.kt
> +                binding.typeLayout.addView(createTypeText("Not Found"))
Кажется, ты не совсем понял в чём суть with

2024-06-18 21:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/MainActivity.kt
> +    private fun createPokemonCard(pokemon: Pokemon): CardView {
Функция выглядит как снаряд для извращений. Я же показывал как генерировать сложный layout при помощи Binding.inflate(xml)

2024-06-18 21:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/MainActivity.kt
> +        return (dp*resources.displayMetrics.density).toInt()
Лучше так не делать, а пользоваться TypedValue

https://developer.android.com/training/multiscreen/screendensities#dips-pels

2024-06-18 21:31 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_about_pokemon.xml
> +    <LinearLayout
Ты и так используешь ConstraintLayout, кажется тут можно обойтись только им, без LinearLayout с весами

2024-06-18 21:31 UTC, pzinkevich42innowise commented on app/src/main/res/values/colors.xml
> +
Лучше такие изменения просто так не делать

2024-06-19 19:35 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/AboutPokemonActivity.kt
> +            setPadding(5)
а тут параметр в dp принимается, или в пикселях?

2024-06-19 19:35 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/MainActivity.kt
> +            dp + 0.5f,
А зачем добавлять 0.5?

2024-06-19 19:37 UTC, pzinkevich42innowise commented on app/src/main/res/layout/pokemon_card.xml
> +            android:layout_height="100dp"
тут 100, а у картинки wrapContent, в идеале как-то консистентно должно быть

2024-06-19 19:38 UTC, pzinkevich42innowise commented
Есть вопросы, ответь на них тут, и если всё гуд - сможешь влить. Апдейты пока не нужны

2024-06-19 19:52 UTC, UdovikArtem commented on app/src/main/java/com/example/pokemonproject/AboutPokemonActivity.kt
> +            setPadding(5)
в пикселях

2024-06-19 19:52 UTC, UdovikArtem commented on app/src/main/java/com/example/pokemonproject/MainActivity.kt
> +            dp + 0.5f,
Для корректного округления

2024-06-19 19:58 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/AboutPokemonActivity.kt
> +            setPadding(5)
А мы в пикселях ничего не устанавливаем...

2024-06-19 19:58 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/MainActivity.kt
> +            dp + 0.5f,
Для округления есть функции округления

2024-06-20 05:06 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonproject/AboutPokemonActivity.kt
> +        }
Добавил в следующем файле функцию, чтобы ей не пользоваться

2024-06-20 05:06 UTC, pzinkevich42innowise approved these changes

2024-06-20 07:18 UTC, merged